$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: sentiment-deployment
endpoint_name: sentiment-analysis-endpoint
model: azureml:sentiment-analysis-transformer:latest
code_configuration:
  code: .
  scoring_script: score.py
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: conda.yml
instance_type: Standard_DS3_v2
